use veilid_core::{
    BareKeyPair, BareOpaqueRecordKey, BarePublicKey, BareRecordKey, BareSecretKey,
    BareSharedSecret, CryptoKind,
};

use crate::{
    proto,
    serialisation::{
        DeserialisationError, SerialisableV1, SerialisationError, impl_v1_proto_conversions,
    },
};

pub(crate) mod v1 {
    // include the proto code generated by prost_build::compile_protos in build.rs
    pub(crate) mod veilid {
        include!(concat!(env!("OUT_DIR"), "/v1.veilid.rs"));
    }
    pub(crate) mod intersect {
        include!(concat!(env!("OUT_DIR"), "/v1.intersect.rs"));
    }
}

// ==== proto conversions for veilid types ====
// (conversions for intersect types are colocated with their model definitions)

// Nonce is just a raw byte array, no cryptokind
// impl From<&veilid_core::Nonce> for proto::v1::veilid::Nonce {
//     fn from(value: &veilid_core::Nonce) -> Self {
//         Self {
//             data: value.to_vec(),
//         }
//     }
// }

// impl From<&proto::v1::veilid::Nonce> for veilid_core::Nonce {
//     fn from(value: &proto::v1::veilid::Nonce) -> Self {
//         Self::new(&value.data)
//     }
// }

impl SerialisableV1 for veilid_core::Nonce {
    type Proto = proto::v1::veilid::Nonce;

    fn to_proto(&self) -> Result<Self::Proto, SerialisationError> {
        Ok(Self::Proto {
            data: self.to_vec(),
        })
    }

    fn from_proto(proto: Self::Proto) -> Result<Self, DeserialisationError> {
        Ok(Self::new(&proto.data))
    }
}

impl_v1_proto_conversions! {veilid_core::Nonce}

// the bulk of veilid types are just cryptotyped byte arrays
// we can automatically generate the proto conversions with a macro mapping the kind and data fields
// (gotta include the Bare- variant in the macro cause i can't concatenate identifiers in a macro)
macro_rules! impl_proto_veilid_typed {
    ($name:ident, $bare:ident) => {
        impl From<proto::v1::veilid::$name> for veilid_core::$name {
            fn from(value: proto::v1::veilid::$name) -> Self {
                Self::new(
                    CryptoKind::from(value.kind),
                    veilid_core::$bare::new(&value.data),
                )
            }
        }

        impl From<&veilid_core::$name> for proto::v1::veilid::$name {
            fn from(value: &veilid_core::$name) -> Self {
                Self {
                    kind: value.kind().into(),
                    data: value.value().to_vec(),
                }
            }
        }
    };
}

impl_proto_veilid_typed!(PublicKey, BarePublicKey);
impl_proto_veilid_typed!(SecretKey, BareSecretKey);
impl_proto_veilid_typed!(HashDigest, BareHashDigest);
// impl_proto_veilid_typed!(SharedSecret, BareSharedSecret);
impl_proto_veilid_typed!(MemberId, BareMemberId);

impl SerialisableV1 for veilid_core::SharedSecret {
    type Proto = proto::v1::veilid::SharedSecret;

    fn to_proto(&self) -> Result<Self::Proto, SerialisationError> {
        Ok(Self::Proto {
            kind: self.kind().into(),
            data: self.value().to_vec(),
        })
    }

    fn from_proto(proto: Self::Proto) -> Result<Self, DeserialisationError> {
        Ok(Self::new(
            CryptoKind::from(proto.kind),
            veilid_core::BareSharedSecret::new(&proto.data),
        ))
    }
}

impl_v1_proto_conversions! {veilid_core::SharedSecret}
// TODO: also replace all the other veilid proto serialisation with the SerialisableV1 + impl_v1_proto_conversions macro
// instead of the manual From impls here

// KeyPair is a bit different, so a manual impl here:
impl From<&veilid_core::KeyPair> for proto::v1::veilid::KeyPair {
    fn from(value: &veilid_core::KeyPair) -> Self {
        Self {
            kind: value.kind().into(),
            key: value.key().into(),
            secret: value.secret().into(),
        }
    }
}

impl From<proto::v1::veilid::KeyPair> for veilid_core::KeyPair {
    fn from(value: proto::v1::veilid::KeyPair) -> Self {
        Self::new(
            CryptoKind::from(value.kind),
            BareKeyPair::new(
                BarePublicKey::new(&value.key),
                BareSecretKey::new(&value.secret),
            ),
        )
    }
}

// and then likewise for RecordKey. this one's a tad more involved and also fallible
// TODO: should i make all the impls in this file TryFrom for consistency or not?
impl TryFrom<&veilid_core::RecordKey> for proto::v1::veilid::RecordKey {
    type Error = SerialisationError;
    fn try_from(value: &veilid_core::RecordKey) -> Result<Self, Self::Error> {
        Ok(Self {
            kind: value.kind().into(),
            key: value.value().key().to_vec(),
            default_encryption: value
                .value()
                .encryption_key()
                // the default encryption key is optional in veilid,
                // but in intersect we always require it to be present
                .ok_or(SerialisationError::MissingDefaultEncryptionKey)?
                .to_vec(),
        })
    }
}

impl From<proto::v1::veilid::RecordKey> for veilid_core::RecordKey {
    fn from(value: proto::v1::veilid::RecordKey) -> Self {
        Self::new(
            CryptoKind::from(value.kind),
            BareRecordKey::new(
                BareOpaqueRecordKey::new(&value.key),
                Some(BareSharedSecret::new(&value.default_encryption)),
            ),
        )
    }
}
