// include the proto code generated by prost_build::compile_protos in build.rs

pub(crate) mod intersect {
    pub(crate) mod v1 {
        include!(concat!(env!("OUT_DIR"), "/intersect.v1.rs"));
    }
}

pub(crate) mod veilid {
    include!(concat!(env!("OUT_DIR"), "/veilid.rs"));
}

impl From<&veilid_core::CryptoKey> for self::veilid::CryptoKey {
    fn from(value: &veilid_core::CryptoKey) -> Self {
        let chunks: Vec<u32> = value
            .bytes
            .chunks_exact(4)
            .map(|chunk| chunk.try_into().unwrap())
            .map(u32::from_le_bytes)
            .collect();

        Self {
            u0: chunks[0],
            u1: chunks[1],
            u2: chunks[2],
            u3: chunks[3],
            u4: chunks[4],
            u5: chunks[5],
            u6: chunks[6],
            u7: chunks[7],
        }
    }
}

impl From<self::veilid::CryptoKey> for veilid_core::CryptoKey {
    fn from(value: self::veilid::CryptoKey) -> Self {
        let mut bytes = Vec::with_capacity(32);
        bytes.extend_from_slice(&value.u0.to_le_bytes());
        bytes.extend_from_slice(&value.u1.to_le_bytes());
        bytes.extend_from_slice(&value.u2.to_le_bytes());
        bytes.extend_from_slice(&value.u3.to_le_bytes());
        bytes.extend_from_slice(&value.u4.to_le_bytes());
        bytes.extend_from_slice(&value.u5.to_le_bytes());
        bytes.extend_from_slice(&value.u6.to_le_bytes());
        bytes.extend_from_slice(&value.u7.to_le_bytes());

        Self {
            bytes: bytes.try_into().unwrap(),
        }
    }
}

impl From<&veilid_core::Nonce> for self::veilid::Nonce {
    fn from(value: &veilid_core::Nonce) -> Self {
        let chunks: Vec<u32> = value
            .bytes
            .chunks_exact(4)
            .map(|chunk| chunk.try_into().unwrap())
            .map(u32::from_le_bytes)
            .collect();

        Self {
            u0: chunks[0],
            u1: chunks[1],
            u2: chunks[2],
            u3: chunks[3],
            u4: chunks[4],
            u5: chunks[5],
        }
    }
}

impl From<self::veilid::Nonce> for veilid_core::Nonce {
    fn from(value: self::veilid::Nonce) -> Self {
        let mut bytes = Vec::with_capacity(24);
        bytes.extend_from_slice(&value.u0.to_le_bytes());
        bytes.extend_from_slice(&value.u1.to_le_bytes());
        bytes.extend_from_slice(&value.u2.to_le_bytes());
        bytes.extend_from_slice(&value.u3.to_le_bytes());
        bytes.extend_from_slice(&value.u4.to_le_bytes());
        bytes.extend_from_slice(&value.u5.to_le_bytes());

        Self {
            bytes: bytes.try_into().unwrap(),
        }
    }
}
